
name = "whatsapp-cloudflare-workers-api-work"
main = "./Example/example.ts"
compatibility_date = "2025-02-24"
compatibility_flags = [ "nodejs_compat_v2" ]
logpush = true


[[r2_buckets]]
binding = 'R2_whatsappCloudflareWorkers'
bucket_name = 'whatsapp-cloudflare-workers-production'
